version: "3.3"

networks:
  app:
    driver: bridge
  db:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data/
    networks:
      - db
    env_file: .global.env
    container_name: postgres
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    networks:
      - db
    env_file: .global.env
    container_name: pgadmin
    depends_on:
      - postgres
    restart: always

  backend_app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app
      - db
    env_file: .global.env
    restart: always
    container_name: backend
    depends_on:
      - postgres

  front_app:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app
    restart: always
    container_name: frontend
    depends_on:
      - backend_app

volumes:
  postgres:
